= Ask Yourself These Five Questions Before Scheduling
Benjamin Vasko
2018-03-01
:jbake-type: post
:jbake-status: published
:idprefix:

=== What are my school’s priorities?
If you want to know what a school values, look at how it orders its day. Subjects considered essential rightly receive more class time. So before you make your school’s schedule, know what is important to your school. Do the humanities take precedence over STEM or vice versa? Do you see your flex period, which allows students to receive one-to-one attention, as very important for student success? Answering these types of questions first will make your school scheduling a lot easier.

=== Which subject should be first?
Students are more alert and ready to learn early in the school day. Take advantage of this by putting a particularly difficult or important subject first. By using our school schedule maker, you can easily do this by assigning a particular class to a particular period.

=== Which subjects should be before and after lunch?
Lunch gives students (and teachers) a much needed break and energy boost. However, the class immediately prior can be a struggle. Think twice about putting a difficult class in its slot. Lots of schools find it beneficial to have a lighter subject taught at this time. Likewise, the class immediately after lunch deserves some thought as well. The extra energy should be used well, but gym class might not be the best option given their full stomachs. Again, whatever you decide is easily taken care of with our school scheduling software.

=== Which subjects should be back-to-back?
Sometimes the sequence of classes relative to one another is just as important as their order in the day. Think through what classes would pair well together. Math and then history? Spanish before English? Music after gym? Or maybe back-to-back science classes would allow for science labs. Either way, sequencing your subjects appropriately is an effective way to promote learning.

=== Which teachers would benefit by having prep periods together?
The school schedule not only dictates when students have which classes when, it also determines when teachers have prep periods. Teachers who teach the same grade level would greatly benefit from having a common prep period during the week since it allows them to collaborate and plan together without having to setup a separate meeting time. If you utilize professional learning communities (PLCs), providing a common prep for each PLC allows its members to meet during the school day instead of before or after school. This is a great convenience for your teachers and demonstrates that you value their work. While using our school scheduler, assigning the same ‘Unavailable Period’ to each teacher who needs a common prep period will ensure that they are not scheduled to teach during that time and will be free to meet.
